language: generic
sudo: required
services:
- docker
script:
- docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/build.sh armhf"
before_deploy:
- .travis/decrypt.sh
deploy:
- provider: releases
  skip_cleanup: true
  file: "*.snap"
  file_glob: true
  api_key:
    secure: GknTd6LVfwAqNSg86v5ctbjl9Qb2n+mV0Mpih+1I6vsgu9CkU0YP0om8XvhChfxvn7UB/nuRWQuWhG+G6sVo7Vy16mBRUavXi9RKYc1pC0xto7xQkGhl+MGvwijxoRvKf4Hp6lKMfJn7bF8m6Rdld/i30a0CQLTuuISK5Kxuy6AfrGnf44iHHot+QqZh4TApl4TOJ9FEGLZcT7abSpwLgYDAbJwHuJixU1BW9faOw0HLkCgwJcwGKS62ASTGVm4O63dWASPti3TsVxPkGv18mv5TnFTDcuGvSewKa9x4vGzKl6WHSxyh2UlbmuJtzBEsdLVDSBOwwgNG7yBmKn/5s1pqufiOXrWgK3nnOsokuEbS9oZzo0gVzPiPlIyj7RJw+/aEyvDvclJPjsVbx+CQbIhPZlwzwekqTv8Gmo+LgW+ikIecJAukGNFncZyCVPKFyJi+ZXVrfhNlEWOz8gMefwtBkE1QZepUf5Pm3MnPQeOrSR4UbCOKB3qBjsAe/eeG+V3h8+rNzOmbnVdpeQCpkBJtC7E6Mgny/F4MNNBRRuOawQXLdlXWETMVeknJ26Hn6X2OttRcWXAlqNgvL/9oWwDkl/KEO8IEyewf94M+WQrCXNZUTTNocewWUUS3rdifRKnDHrEjP4m/Z+u8GQw3eaoZe8uz8vLxsWsmrUHUtgE=
  on:
    repo: fuzeman/orangepi-zero-kernel
    tags: true
- provider: script
  skip_cleanup: true
  script:
  - docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/push.sh $TRAVIS_TAG"
  on:
    repo: fuzeman/orangepi-zero-kernel
    tags: true
#- provider: script
#  skip_cleanup: true
#  script:
#  - docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/push.sh"
#  on:
#    repo: fuzeman/orangepi-zero-kernel
#    branch: master
