name: orangepi-zero-kernel
summary: Minimal kernel for the Orange Pi Zero
version: 4.10.8-alpha.1
type: kernel

description: |
  Kernel for the Orange Pi Zero with the bare minimum drivers and modules.

  See https://github.com/fuzeman/orangepi-zero-kernel for details.

architectures: [armhf]
confinement: strict
grade: devel

parts:
    kernel:
        plugin: kernel

        source: https://github.com/fuzeman/linux-ubuntu-zesty.git
        source-commit: b3793a6ca016740dc3393a873e01b8a5a835b970
        source-depth: 1
        source-type: git

        build-packages: [bc, cpio, kmod, libssl-dev]

        kdefconfig: ['--makefile=debian/snapcraft.mk', 'branch=sunxi','flavour=orangepi-zero', 'config']
        kernel-image-target: zImage

        kconfigs:
          - CONFIG_LOCALVERSION="-orangepi-zero"
          - CONFIG_SQUASHFS=m
          - CONFIG_DEVPTS_MULTIPLE_INSTANCES=y

        kernel-initrd-modules:
          - squashfs

        kernel-device-trees:
          - sun8i-h2-plus-orangepi-zero

        prepare: |
          touch .scmversion

    firmware:
        plugin: fm-firmware

        source: https://github.com/fuzeman/linux-firmware.git
        source-commit: 50e1695201e070d41ba3c2c8682b33638aec0e44
        source-depth: 1
        source-type: git

        fm-firmware:
          - xr819
